name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
          cache: 'npm'

      - name: Apply dependency fixes
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          cp .github/package.json.fixup package.fix.json
          jq -s '.[0] * .[1]' package.json package.fix.json > package.combined.json
          mv package.combined.json package.json

      - name: Setup .npmrc
        run: |
          echo "legacy-peer-deps=true" >> .npmrc
          echo "node-linker=hoisted" >> .npmrc
          echo "prefer-dedupe=true" >> .npmrc
          echo "strict-peer-dependencies=false" >> .npmrc

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps --no-audit --no-fund
          npm install --save-dev critters

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: NODE_OPTIONS='--max_old_space_size=4096' npm run build

      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod --force'
          working-directory: ./

      - name: Deploy to Vercel (Preview)
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
